### ISSUE TITLE
Game crashes upon opening when JCursor is in the Mods folder

### ISSUE THREAD

**Issue by Fanrail** [jie65535/JMods#1]
After Steamodded does its loading thing, I got a crash on the game.
Here is the message from the death screen:
Oops! The game crashed:
[SMODS JCursor "JCursor.lua"]:53: attempt to call field 'registerUIElement' (a nil value)

Additional Context:
Balatro Version: 1.0.1n-FULL (Локализация от Nitablade, v1.1.6)
Modded Version: 1.0.0~ALPHA-1229b-STEAMODDED
LÖVE Version: 11.5.0
Lovely Version: 0.6.0
Steamodded Mods:
    1: Hand Preview RU by Toeler (Перевод от ZarenOFF) [ID: handpreview]
    2: Neow Blessings by kjossul [ID: NeowBlessings]
    3: JokerSellValue by OppositeWolf770 [ID: JokerSellValue, Priority: 100000, Version: 1.2.1]
    4: Card Sleeves by LarsWijn [ID: CardSleeves, Priority: -1, Version: 1.4.8, Uses Lovely]
    5: BalaLib by Toeler [ID: balalib, Priority: -10]
    6: Fold Button by happinyz [ID: FoldButton]
    7: Escape Exit Button by Steamo [ID: EscapeExitButton]
    8: Main Menu Tweaks by termisaal [ID: MainMenuTweaks]
    9: BalatrOverlay by cantlookback [ID: balover]
    10: Better Balatro (Myst's April Fools) by Mysthaps [ID: MystAprilFools]
    11: Better Mouse And Gamepad by Kooluve [ID: BetterMouseAndGamepad, Priority: -10000, Version: 1.0.6c]
    12: Keyboard Shortcuts DorkDad by DorkDad141 [ID: keyboard_dorkdad]
    13: Quick Load by Asobi [ID: QuickLoad]
    14: Rumble by WilsontheWolf [ID: Rumble]
    15: Balatro Safety by Zei33 [ID: balatro-safety, Version: 1.0.0]
    16: J Cursor by Jie65535, MarioMak967 [ID: JCursor]
    17: JokerDisplay by nh6574 [ID: JokerDisplay, Priority: -100000, Version: 1.7.1.1]
Lovely Mods:
    1: ProperRussian

Stack Traceback
===============
(3) main chunk of file 'JCursor.lua' at line 53 (from mod with id JCursor)
(4) Lua global 'loadMods' at Steamodded file 'src/loader.lua:570' 
Local variables:
 modsDirectory = string: "C:\\Users\\nicko\\AppData\\Roaming\\Balatro\\Mods"
 header_components = table: 0x029432f0  {version:table: 0x02943a40, id:table: 0x02943500, conflicts:table: 0x02943930 (more...)}
 json_spec = table: 0x02943bf8  {provides:table: 0x02944478, __:table: 0x029443f8, version:table: 0x029441b8 (more...)}
 used_prefixes = table: 0x029444f8  {balo:balover, casl:CardSleeves, jcur:JCursor, rumb:Rumble, bmag_k:BetterMouseAndGamepad (more...)}
 lovely_directories = table: 0x02944520  {1:C:\Users\nicko\AppData\Roaming\Balatro\Mods/CardSleeves-1.4.8/, 2:C:\Users\nicko\AppData\Roaming\Balatro\Mods/ProperRussian/ (more...)}
 processDirectory = Lua function '?' (defined at line 184 of chunk [SMODS _ "src/loader.lua"])
 keyset = table: 0x02810930  {1:-100000, 2:-10000, 3:-10, 4:-1, 5:0, 6:100000}
 check_dependencies = Lua function '?' (defined at line 418 of chunk [SMODS _ "src/loader.lua"])
 (for generator) = C function: builtin#6
 (for state) = table: 0x02810930  {1:-100000, 2:-10000, 3:-10, 4:-1, 5:0, 6:100000}
 (for control) = number: 5
 _ = number: 5
 priority = number: 0
 (for generator) = C function: builtin#6
 (for state) = table: 0x02845f90  {1:table: 0x027feec8, 2:table: 0x02462540, 3:table: 0x0292b0c0, 4:table: 0x024f8348 (more...)}
 (for control) = number: 3
 _ = number: 3
 mod = table: 0x0292b0c0  {version:0.0.0, id:JCursor, main_file:JCursor.lua, can_load:true, badge_colour:table: 0x0278dda8 (more...)}
(5) Lua global 'initSteamodded' at Steamodded file 'src/loader.lua:652' 
(6) Lua method 'start_up' at file 'game.lua:211'
Local variables:
 self = table: 0x0222f020  {SPEEDFACTOR:1, F_GUIDE:false, keybind_mapping:table: 0x02239f70, F_CRASH_REPORTS:false (more...)}
 settings = string: "return {[\"version\"]=\"1.0.1n-FULL (Локализация от Nitablade, v1.1.6)\",[\"reduced_motion\"]=false,[\"paused\"]=false,[\"QUEUED_CHANGE\"]={},[\"COMP\"]={[\"prev_name\"]=\"\",[\"name\"]=\"\",[\"score\"]=2144011555.791,},[\"colourblind_option\"]=true,[\"play_button_pos\"]=2,[\"CUSTOM_DECK\"]={[\"Collabs\"]={[\"Spades\"]=\"collab_SK\",[\"Hearts\"]=\"collab_TBoI\",[\"Diamonds\"]=\"default\",[\"Clubs\"]=\"collab_PC\",},},[\"HandPreview\"]={[\"preview_count\"]=3,[\"include_breakdown\"]=false,[\"include_facedown\"]=false,[\"position_locked\"]=true,[\"anchor\"]=\"Top Right\",},[\"crashreports\"]=false,[\"tutorial_progress\"]={[\"hold_parts\"]={[\"first_hand_3\"]=true,[\"small_blind\"]=true,[\"big_blind\"]=true,[\"first_hand_4\"]=true,[\"second_hand\"]=true,[\"shop_1\"]=true,[\"first_hand_2\"]=true,[\"first_hand\"]=true,},[\"section\"]=\"second_hand\",[\"completed_parts\"]={[\"first_hand\"]=true,[\"first_hand_3\"]=true,[\"small_blind\"]=true,[\"big_blind\"]=true,[\"first_hand_4\"]=true,[\"shop_1\"]=true,[\"first_hand_section\"]=true,[\"first_hand_2\"]=true,[\"second_hand\"]=true,},},[\"language\"]=\"ru\",[\"tutorial_complete\"]=true,[\"WINDOW\"]={[\"vsync\"]=1,[\"display_names\"]={[1]=\"1\",},[\"screenmode\"]=\"Borderless\",[\"DISPLAYS\"]={[1]={[\"screen_resolutions\"]={[\"strings\"]={[1]=\"1920 X 1080\",},[\"values\"]={[1]={[\"w\"]=1920,[\"h\"]=1080,},},},[\"screen_res\"]={[\"w\"]=1920,[\"h\"]=1080,},[\"DPI_scale\"]=1,[\"MONITOR_DIMS\"]={[\"height\"]=1080,[\"width\"]=1920,},},},[\"selected_display\"]=1,},[\"run_stake_stickers\"]=true,[\"GAMESPEED\"]=4,[\"SOUND\"]={[\"volume\"]=100,[\"music_volume\"]=100,[\"game_sounds_volume\"]=100,},[\"music_control\"]={[\"current_track\"]=\"\",[\"desired_track\"]=\"\",[\"lerp\"]=1,},[\"ACHIEVEMENTS_EARNED\"]={[\"card_discarder\"]=true,[\"heads_up\"]=true,[\"retrograde\"]=true,[\"shattered\"]=true,[\"_100000k\"]=true,[\"cartomancy\"]=true,[\"you_get_what_you_get\"]=true,[\"mid_stakes\"]=true,[\"completionist\"]=true,[\"low_stakes\"]=true,[\"nest_egg\"]=true,[\"ante_upper\"]=true,[\"astronomy\"]=true,[\"royale\"]=true,[\"_1000k\"]=true,[\"_10k\"]=true,[\"extreme_couponer\"]=true,[\"speedrunner\"]=true,[\"legendary\"]=true,[\"roi\"]=true,[\"clairvoyance\"]=true,[\"ante_up\"]=true,[\"card_player\"]=true,},[\"screenshake\"]=50,[\"current_setup\"]=\"New Run\",[\"profile\"]=1,[\"ambient_control\"]={[\"ambientFire1\"]={[\"per\"]=1.1,[\"vol\"]=0,},[\"ambientOrgan1\"]={[\"per\"]=0.7,[\"vol\"]=0,},[\"ambientFire2\"]={[\"per\"]=1.05,[\"vol\"]=0,},[\"ambientFire3\"]={[\"per\"]=1,[\"vol\"]=0,},},[\"DEMO\"]={[\"win_CTA_shown\"]=true,[\"quit_CTA_shown\"]=true,[\"timed_CTA_shown\"]=true,[\"total_uptime\"]=15.031750417772,},[\"GRAPHICS\"]={[\"texture_scaling\"]=2,[\"crt\"]=0,[\"shadows\"]=\"On\",[\"bloom\"]=1,},}"
 settings_ver = nil
 new_colour_proto = table: 0x02237800  {Spades:table: 0x02237a68, Hearts:table: 0x02237918, Diamonds:table: 0x022379d0 (more...)}
 sound_files = table: 0x025d70c8  {1:ambientFire1.ogg, 2:ambientFire2.ogg, 3:ambientFire3.ogg, 4:ambientOrgan1.ogg (more...)}
 shader_files = table: 0x02166ec8  {1:CRT.fs, 2:background.fs, 3:booster.fs, 4:debuff.fs, 5:dissolve.fs, 6:flame.fs (more...)}
(7) Lua field 'load' at file 'main.lua:945'
(8) Lua function '?' at file 'main.lua:892' (best guess)
(9) global C function 'xpcall'
(10) LÖVE function at file 'boot.lua:368' (best guess)
Local variables:
 result = boolean: true
 main = nil
(11) global C function 'xpcall'
(12) LÖVE function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '(LÖVE Function)' (defined at line 355 of chunk [love "boot.lua"])
 inerror = boolean: true
 deferErrhand = Lua function '(LÖVE Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(LÖVE Function)' (defined at line 355 of chunk [love "boot.lua"])

Moving this mod's folder to the trashbin fixed the issue, but, obviously, left me without the mod's content. Please, help me.

**Comment by jie65535** [comment]
Thank you for your feedback. I have removed the GUI to fix the issue. Please feel free to continue using it.

**Comment by Fanrail** [comment]
Thanks, now the game does not crash upon opening.
